version: 2
jobs:
    build:
        docker:
            - image: circleci/node:6
        steps:
            - checkout
            - run:
                name: update-npm
                command: npm install
            - run:
                name: run-build
                command: npm run build:ci